name: "Retry Example"
on:
  workflow_dispatch:
    inputs:
      exit-code:
        required: true
jobs:
  retry-example:
    runs-on: ubuntu-latest
    steps:
      - name: 失敗するステップ
        run: exit ${{ github.event.inputs.exit-code}}
      - name: リトライ
        if: failure()
        run: echo "リトライ成功"
