name: "Retry Example"
on:
  workflow_dispatch:
    inputs:
      exit-code:
        required: true
jobs:
  retry-example:
    runs-on: ubuntu-latest
    steps:
      - name: 失敗すればリトライ
        run: exit ${{ github.event.inputs.exit-code}} || echo "リトライ成功"
